"""part_map.py + candidates.csv + parts.json -> docs/13_part_map_ja.md and docs/assembly_ja/part_map_ja.html
    python docs/parts/build_partmap.py            (write)
    python docs/parts/build_partmap.py --check    (fail if the map is incomplete or the md is stale)"""
import base64
import html
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
import part_map as pm  # noqa: E402

MD = os.path.join(ROOT, "docs", "13_part_map_ja.md")
HTML = os.path.join(ROOT, "docs", "assembly_ja", "part_map_ja.html")
SIDE = {"picker": "ピッカー", "microscope": "顕微鏡側", "reference": "参考(外形のみ)"}


def rows():
    parts = pm.load_parts()
    pids = pm.load_pids()
    out = []
    for g in pm.GROUPS:
        steps = pm.steps_of_group(g, parts)
        out.append(dict(g, steps=("工程 " + ", ".join(map(str, steps))) if steps else "—",
                        pid_txt=", ".join(g["pids"]) or "—",
                        cad=", ".join(sorted({re.sub(r"_\d+$", "_*", pm.strip(k)) for k in parts
                                              if pm.group_of(k) == [g["n"]]}))))
    rev = []
    for pid, r in pids.items():
        ns = [g["n"] for g in pm.GROUPS if pid in g["pids"]]
        rev.append(dict(pid=pid, item=r["item"], cat=r["category"], ns=", ".join(map(str, ns))))
    return out, rev


def cell(x):
    return str(x).replace("|", "\\|")


def markdown():
    out, rev = rows()
    L = ["<!-- GENERATED by docs/parts/build_partmap.py from docs/parts/part_map.py - edit part_map.py -->",
         "# 部品の対応表(どこの部品が何に当たるか)", "",
         "図の番号 1–27 が、実物の部品、CAD のパーツ名、部品候補リストの番号(P01–P42)、組立工程、関係する実測項目をつなぎます。"
         "W-B(ステージが動く)構成、8° ヘッド、IX-ULWCD の状態で描いています。番号はこの表と図で共通です。", "",
         "![全体図(番号付き)](assembly_ja/img/partmap_overall.png)", "",
         "![ヘッド周りの拡大図(番号付き)](assembly_ja/img/partmap_head.png)", "",
         "全体図では架台、3 軸、電装、顕微鏡側に番号を付け、ヘッド周り(14–19、24)は拡大図に付けています。"
         "20 と 22 は定盤の上、架台の外側に置く箱(ポンプと制御箱)です。", "",
         "## 対応表", "",
         "区分は、製作 = 図面を起こして作る、購入 = 市販品を買う、既存 = 研究室にあるものを使う、顕微鏡 = 顕微鏡側の機器(ピッカーとしては作らない)です。", "",
         "| 番号 | 部品 | 役割 | 区分 | 部品候補(P) | 組立 | 関係する実測など | CAD のパーツ名 |",
         "|---|---|---|---|---|---|---|---|"]
    for r in out:
        L.append(f"| {r['n']} | {cell(r['name'])} | {cell(r['role'])} | {r['kind']} | {r['pid_txt']} | {r['steps']} | "
                 f"{cell(r['meas'] or '—')} | `{cell(r['cad'])}` |")
    L += ["", "## 部品候補の番号から引く", "",
          "発注や見積のときに、部品候補リスト(`12_parts_candidates.md`)の番号から図の番号を引くための表です。", "",
          "| 部品候補 | 分類 | 品目(候補リストの表記) | 図の番号 |", "|---|---|---|---|"]
    for r in rev:
        L.append(f"| {r['pid']} | {cell(r['cat'])} | {cell(r['item'])} | {r['ns']} |")
    L += ["", "## この表の保ち方", "",
          "対応は `docs/parts/part_map.py` の一か所だけに書いてあります。組立工程の割り当てもここにあり、ビューアの工程図もここから作ります。"
          "`python tools/build_all.py --check` と CI のテストは、W-B の CAD パーツがどれか一つの番号にだけ入っていること、"
          "部品候補 P01–P42 がすべてどこかの番号に入っていることを確かめます。部品を増やしたら、`part_map.py` に一行足して再生成してください。", ""]
    return "\n".join(L)


def img(name):
    fn = os.path.join(ROOT, "docs", "assembly_ja", "img", name)
    return "data:image/png;base64," + base64.b64encode(open(fn, "rb").read()).decode()


def page():
    import markdown as mdlib
    md = markdown()
    md = re.sub(r"^<!--.*?-->\n", "", md)
    md = md.replace("assembly_ja/img/partmap_overall.png", img("partmap_overall.png"))
    md = md.replace("assembly_ja/img/partmap_head.png", img("partmap_head.png"))
    body = mdlib.markdown(md, extensions=["tables", "sane_lists"])
    body = body.replace("<table>", '<div class="tbl"><table>').replace("</table>", "</table></div>")
    guide = open(os.path.join(ROOT, "docs", "assembly_ja", "guide.src.html"), encoding="utf-8").read()
    style = guide[guide.index("<style>"):guide.index("</style>") + len("</style>")]
    fonts = guide[guide.index("<link rel=\"preconnect\""):guide.index("<style>")]
    extra = """<style>
main h1{margin-bottom:8px} main h2{margin-top:22px} main img{width:100%;height:auto;border:1px solid var(--line);
border-radius:6px;margin:6px 0} td,th{font-size:13px;vertical-align:top} td:first-child{font-weight:700;text-align:center}
td code{font-size:11px;word-break:break-all} td:nth-child(4),td:nth-child(6),th{white-space:nowrap}
</style>"""
    return f"<title>IX73 ピッカー 部品の対応表</title>\n{fonts}{style}\n{extra}\n<main>\n{body}\n</main>\n"


if __name__ == "__main__":
    errs = pm.check()
    if errs:
        sys.exit("part map incomplete:\n  " + "\n  ".join(errs))
    if "--check" in sys.argv:
        if open(MD, encoding="utf-8").read() != markdown():
            sys.exit("docs/13_part_map_ja.md is stale: run tools/build_all.py")
        print("part map complete and up to date")
    else:
        open(MD, "w", encoding="utf-8").write(markdown())
        open(HTML, "w", encoding="utf-8").write(page())
        print("ok", len(pm.GROUPS), "groups")
